//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class partycharacter
    {
        public partycharacter()
        {
            this.characterskills = new HashSet<characterskill>();
        }
    
        public int Id { get; set; }
        public int PartyId { get; set; }
        public int CharacterCardId { get; set; }
    
        public virtual charactercard charactercard { get; set; }
        public virtual ICollection<characterskill> characterskills { get; set; }
        public virtual party party { get; set; }
    }
}
